set nocompatible
execute 'set rtp^=' . expand('<sfile>:p:h:h')
call jetpack#begin(expand('<sfile>:p:h'))
call jetpack#add('neoclide/coc.nvim', { 'branch': 'release' })
call jetpack#add('junegunn/fzf', { 'do': { -> fzf#install() } })
call jetpack#add('junegunn/fzf.vim', { 'opt': 1 })
call jetpack#add('yuki-yano/fzf-preview.vim', { 'branch': 'release/rpc', 'for': ['lisp'] })
call jetpack#add('lotabout/skim', { 'dir': expand('<sfile>:p:h'). '/pack/skim', 'do': './install' })
call jetpack#add('dracula/vim', { 'as': 'dracula' })
call jetpack#add('vlime/vlime', { 'rtp': 'vim' })
call jetpack#add('vim-test/vim-test') "Issue 15
call jetpack#add('https://github.com/dense-analysis/ale')
call jetpack#add('junegunn/goyo.vim', { 'for': 'markdown' })
call jetpack#add('tani/ddc-fuzzy', { 'commit': 'e84eadc7ea1b4d7854840291e5709329432fd159' })
call jetpack#end()

autocmd! User JetpackGoyoVim let g:is_loaded_goyo_user = 1
