= Jetpack.vim
:icons:
:sectlinks:
:toc: left
:source-highlighter: rouge

Jetpack.vim is a plugin manager for https://vim.org[Vim], https://neovim.io[Neovim], and https://github.com/terrychou/iVim[iVim].

== Features

* Lightning-fast startup time
** It optimizes the search path of plugins and runtime files.
* Single file installation
** You need to just download a single file and put it.
* First-class Lua support
** This plugin is not written in Lua but we provide a Lua API.
* Fancy User Interface
** You can see a progress of installation with a graphical progress bar.
* `pack/*/start` -free installation
** You can install plugins without `pack/*/start` directory.
* Git-free installation
** You can optionally install plugins without git.

== Installation

The installation is very simple.
You just need to download a single file and put it on the runtimepath.

[source]
----
https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim
----

The following is an example of installation with cURL command.

.Vim for Linux and macOS
[%collapsible]
====
[source]
----
curl -fLo ~/.vim/pack/jetpack/opt/vim-jetpack/plugin/jetpack.vim --create-dirs https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim
----
====

.Neovim for Linux and macOS
[%collapsible]
====
[source]
----
curl -fLo ~/.local/share/nvim/site/pack/jetpack/opt/vim-jetpack/plugin/jetpack.vim --create-dirs https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim
----
====

.Vim for Windows
[%collapsible]
====
[source]
----
curl -fLo %USERPROFILE%\vimfiles\pack\jetpack\opt\vim-jetpack\plugin\jetpack.vim --create-dirs https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim
----
====

.Neovim for Windows
[%collapsible]
====
[source]
----
curl -fLo %USERPROFILE%\AppData\Local\nvim-data\site\pack\jetpack\opt\vim-jetpack\plugin\jetpack.vim --create-dirs https://raw.githubusercontent.com/tani/vim-jetpack/master/plugin/jetpack.vim
----
====

TIP: There exists an option for automatic installation on startup.
Fore more details, see Configuration Snippets.

== Usage

Jetpack was initially implemented as a successor of vim-plug.
Nowadays, we also provide compatibility layers for other plugin managers,
dein.vim, packer.nvim.nvim, and paq.nvim.nvim.
You can use Jetpack as a drop-in replacement of them.
In personal opinion, vim-plug style is the most stable and easy to use.

=== Vim-plug style

=== Dein.vim style

=== Legacy packer.nvim style

=== Modern packer.nvim/ paq.nvim style

== Configuration

=== Configuration Variables

We provides configuration variables to change the internal behaviors:
copying files, downloading plugins.

`g:jetpack_copy_method`::
Jetpack copies files with the external command by default.
Further, Jetpack can copy files with the external command,
Vim's built-in functions, or Neovim's built-in functions.
Note that the most cross-platform way is to use Vim's built-in functions.
The fastest way is to use the Neovim's built-in functions.

`g:jetpack_download_method`::
Jetpack downloads plugins with git by default.
Further, Jetpack can download plugins with git, cURL, and wget
This is useful for environments without git.
Non-git options are not recommended because they are slower than git
as jeptack downloads the whole repository as a tar archive.

[TIP]
.iVim does not have git command.
====
We recommend the following configuration to avoid
the external commands except cURL.
[source, vim]
----
let g:jetpack_copy_method = 'copy'
let g:jetpack_download_method = 'curl'
----
====

=== Configuration Prameters

CAUTION: You might be able to use another configuration parameters,
you can use `on_cmd` in vim-plug style for example,
but it might be going to be removed in the future.
Thus, we recommend you not to use unlisted configuration parameters.

==== Vim-plug style

You can pass the configuration parameters to `Jetpack` command as follows.

[source, vim]
----
Jetpack 'tani/vim-jetpack', { 'as': 'jetpack' }
----

The following is a list of configuration parameters for vim-plug style.

[%autowidth]
|===
|Parameter|Type|Description

|`on`
|`string` or `array`
| On-demand loading plugins by commands, keymaps.

|`for`
|`string` or `array`
| On-demand loading plugins by filetypes.

|`branch`
|`string`
| Install plugins from the specified branch.

|`commit`
|`string`
| Install plugins from the specified commit.

|`tag`
|`string`
| Install plugins from the specified tag.

|`rtp`
|`string`
| Add the specified directory to the runtimepath.

|`do`
|`string` or `function`
| Execute the specified command after installation.

|`as`
|`string`
| Install plugins as the specified name.

|`dir`
|`string`
| Install plugins to the specified directory.

|`frozen`
|`boolean`
| Freeze plugins to the current version.
|===

NOTE: Jetpack mechanically distinguishes `:SomeCommand` and `<Plug>(some-command)`, and the external command, for `on` parameters and `do` parameters.

==== Dein.vim style

You can pass the configuration parameters to `jetpack#add` function as follows.

[source, vim]
----
call jetpack#add('tani/vim-jetpack', { 'name': 'jetpack' })
----

The following is a list of configuration parameters for dein.vim style.
Note that we do not support full features of dein.vim.
We are welcome to your pull requests to improve the compatibility.

[%autowidth]
|===
|Parameter|Type|Description

|`on_cmd`
|`string` or `array`
| On-demand loading plugins by commands.

|`on_ft`
|`string` or `array`
| On-demand loading plugins by filetypes.

|`on_map`
|`string` or `array`
| On-demand loading plugins by keymaps.

|`on_event`
|`string` or `array`
| On-demand loading plugins by events.

|`branch`
|`string`
| Install plugins from the specified branch.

|`commit`
|`string`
| Install plugins from the specified commit.

|`tag`
|`string`
| Install plugins from the specified tag.

|`path`
|`string`
| Install plugins to the specified directory.

|`rtp`
|`string`
| Add the specified directory to the runtimepath.

|`build`
|`string`
| Execute the specified external command after installation.

|`name`
|`string`
| Install plugins as the specified name.

|`merged`
|`boolean`
| Merge plugins to the current runtimepath.

|`frozen`
|`boolean`
| Freeze plugins to the current version.
|===

==== Legacy packer.nvim style

You can pass the configuration parameters to `use` function as follows.

[source, lua]
----
use { 'tani/vim-jetpack', as = 'jetpack' }
----

Note that we do not support full features of packer.nvim.
We are welcome to your pull requests to improve the compatibility.

==== Modern packer.nvim/ paq.nvim style

You can pass the configuration parameters to a table as follows.

[source, lua]
----
{ 'tani/vim-jetpack', as = 'jetpack' }
----

Note that we do not support full features of packer.nvim.
We are welcome to your pull requests to improve the compatibility.

=== Configuration Snippets

==== Automatic installation on startup

==== Automatic plugin installation on startup

== API

CAUTION: You might be able to use other functions, commands, and events.
but it might be going to be removed in the future.
Thus, we recommend you not to use unlisted ones.

=== VimL Functions

=== Lua Functions

=== Commands

=== Events

== Contributing

== License

Copyright (c) 2022 Masaya Taniguchi

The software is released under the MIT License,
see the header of the source code.
